import type {NextPage} from "next";
import Head from "next/head";
import React from "react";
import {CreateAccountForm} from "../components/forms/CreateAccount";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className='flex items-center justify-center'>
                <CreateAccountForm/>
            </main>
        </>
    );
}

export default Home