packages:
  - apps/expo
  - apps/nextjs
  - packages/api
  - packages/db
  - packages/components
  - packages/utils
  - packages/hooks
  - packages/config/*
  # TODO(AbhiShake1): exclude scripts
  - packages/scripts
